### ISSUE TITLE
Pandas warning: chained assignments

### ISSUE THREAD

**Issue by ancpJR** [ANCPLabOldenburg/MEGqc#51]
There are some pandas warning regarding a functionality that s being removed in version 

/envs/megqc/lib/python3.9/site-packages/meg_qc/calculation/metrics/PSD_meg_qc.py:1057: RuntimeWarning: joblib not installed. Cannot run in parallel.
  psds[m_or_g], freqs[m_or_g] = raw.compute_psd(method=method, fmin=psd_params['freq_min'], fmax=psd_params['freq_max'], picks=m_or_g, n_jobs=-1, n_fft=nfft, n_per_seg=nperseg).get_data(return_freqs=True)
/envs/megqc/lib/python3.9/site-packages/meg_qc/calculation/metrics/PSD_meg_qc.py:234: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  brain_bands_df['total_amplitude']['absolute_'+m_or_g] = total_ampl[0]
/envs/megqc/lib/python3.9/site-packages/meg_qc/calculation/metrics/PSD_meg_qc.py:235: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  brain_bands_df['total_amplitude']['relative_'+m_or_g] = 1
Effective window size : 2.000 (s)
/envs/megqc/lib/python3.9/site-packages/meg_qc/calculation/metrics/PSD_meg_qc.py:1057: RuntimeWarning: joblib not installed. Cannot run in parallel.
  psds[m_or_g], freqs[m_or_g] = raw.compute_psd(method=method, fmin=psd_params['freq_min'], fmax=psd_params['freq_max'], picks=m_or_g, n_jobs=-1, n_fft=nfft, n_per_seg=nperseg).get_data(return_freqs=True)
/envs/megqc/lib/python3.9/site-packages/meg_qc/calculation/metrics/PSD_meg_qc.py:234: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

**Comment by Evgeniia-Gapontseva** [comment]
The chained assignments warning in PSD is fixed.

Also 'RuntimeWarning: joblib not installed' is fixed: it will not attempt to run jobs in parallel any more, so we don't need to install joblib.

The updated version can be cloned from git.
